server:
  port: 8888
  
spring:
  application:
    name: erudio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Heberty123/erudio-config-server.git
          #username: username
          #password: password
          default-label: master
          search-paths:
          - 'greeting-service*'